
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered itinerary suggestions based on user interests.
 *
 * - suggestItinerary - A function that generates itinerary suggestions.
 * - AiItinerarySuggestionsInput - The input type for suggestItinerary function.
 * - AiItinerarySuggestionsOutput - The return type for suggestItinerary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiItinerarySuggestionsInputSchema = z.object({
  interests: z
    .string()
    .describe(
      'A comma separated list of travel interests like adventure, luxury, cultural, desert, relaxation, etc.'
    ),
  duration: z.string().describe('The duration of the trip in days.'),
  budget: z.string().describe('The budget for the trip (e.g., low, medium, high).'),
});
export type AiItinerarySuggestionsInput = z.infer<typeof AiItinerarySuggestionsInputSchema>;

const AiItinerarySuggestionsOutputSchema = z.object({
  itinerary: z.string().describe('A detailed travel itinerary based on the user interests.'),
});
export type AiItinerarySuggestionsOutput = z.infer<typeof AiItinerarySuggestionsOutputSchema>;

export async function suggestItinerary(input: AiItinerarySuggestionsInput): Promise<AiItinerarySuggestionsOutput> {
  return suggestItineraryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiItinerarySuggestionsPrompt',
  input: {schema: AiItinerarySuggestionsInputSchema},
  output: {schema: AiItinerarySuggestionsOutputSchema},
  prompt: `You are a travel expert specializing in creating personalized itineraries for Dubai.

  Based on the user's interests, duration, and budget, create a detailed itinerary that covers the best of Dubai.

  Interests: {{{interests}}}
  Duration: {{{duration}}} days
  Budget: {{{budget}}}

  Provide a detailed day-by-day itinerary, including specific activities, attractions, and dining suggestions. Be specific with names and locations.
  Be sure to account for travel time between locations.
  `,
});

const suggestItineraryFlow = ai.defineFlow(
  {
    name: 'suggestItineraryFlow',
    inputSchema: AiItinerarySuggestionsInputSchema,
    outputSchema: AiItinerarySuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('AI model did not return an output. Please try again.');
    }
    return output;
  }
);
